### ISSUE TITLE
[컴포넌트] 아이콘 컴포넌트

### ISSUE THREAD

**Issue by elenfl0122** [ayoung-iya/seulgiroul_jido#1]
### 📌 기능설명

- 지도 페이지의 사이드 바에서 쓰이는 리스트 아이템 컴포넌트의 아이콘

### 📌 레퍼런스

<img alt="image" src="https://github.com/user-attachments/assets/f5006997-50b2-4a1e-8863-137d9cc43ab5">

### 📌 ToDo

- [ ] 아이콘 이미지 ( 식사 /  카페 / 술집 ) 
- [ ] 가게 상호명 / 영업 중 / 찜유무
- [ ] 컴포넌트 클릭 시 모달 오픈
